# Generated by Django 3.1.6 on 2021-02-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
