# Generated by Django 3.1.6 on 2021-02-01 19:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_attachment_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
