# Generated by Django 3.1.6 on 2021-02-04 14:52

from django.db import migrations, models
import tickets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20210202_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d', validators=[tickets.models.validate_file]),
        ),
    ]
