# Generated by Django 3.1.6 on 2021-02-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20210204_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
