# Generated by Django 3.1.6 on 2021-02-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_priority_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_active',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('unsolved', 'Unsolved'), ('close', 'Close')], default='open', max_length=10),
        ),
    ]
